// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/strategy.proto

package bitesla_srv_strategy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StrategyInfo struct {
	CurrentLoginUserID   int64    `protobuf:"varint,1,opt,name=currentLoginUserID,proto3" json:"currentLoginUserID,omitempty"`
	StrategyId           int64    `protobuf:"varint,2,opt,name=strategyId,proto3" json:"strategyId,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Script               string   `protobuf:"bytes,5,opt,name=script,proto3" json:"script,omitempty"`
	Page                 int32    `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	CreateTime           int64    `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64    `protobuf:"varint,9,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StrategyInfo) Reset()         { *m = StrategyInfo{} }
func (m *StrategyInfo) String() string { return proto.CompactTextString(m) }
func (*StrategyInfo) ProtoMessage()    {}
func (*StrategyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a9cfd4cb1c623bb, []int{0}
}

func (m *StrategyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrategyInfo.Unmarshal(m, b)
}
func (m *StrategyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrategyInfo.Marshal(b, m, deterministic)
}
func (m *StrategyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrategyInfo.Merge(m, src)
}
func (m *StrategyInfo) XXX_Size() int {
	return xxx_messageInfo_StrategyInfo.Size(m)
}
func (m *StrategyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StrategyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StrategyInfo proto.InternalMessageInfo

func (m *StrategyInfo) GetCurrentLoginUserID() int64 {
	if m != nil {
		return m.CurrentLoginUserID
	}
	return 0
}

func (m *StrategyInfo) GetStrategyId() int64 {
	if m != nil {
		return m.StrategyId
	}
	return 0
}

func (m *StrategyInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StrategyInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *StrategyInfo) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *StrategyInfo) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *StrategyInfo) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *StrategyInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *StrategyInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type StrategyInfos struct {
	StrategyInfos        []*StrategyInfo `protobuf:"bytes,1,rep,name=strategyInfos,proto3" json:"strategyInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StrategyInfos) Reset()         { *m = StrategyInfos{} }
func (m *StrategyInfos) String() string { return proto.CompactTextString(m) }
func (*StrategyInfos) ProtoMessage()    {}
func (*StrategyInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a9cfd4cb1c623bb, []int{1}
}

func (m *StrategyInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrategyInfos.Unmarshal(m, b)
}
func (m *StrategyInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrategyInfos.Marshal(b, m, deterministic)
}
func (m *StrategyInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrategyInfos.Merge(m, src)
}
func (m *StrategyInfos) XXX_Size() int {
	return xxx_messageInfo_StrategyInfos.Size(m)
}
func (m *StrategyInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_StrategyInfos.DiscardUnknown(m)
}

var xxx_messageInfo_StrategyInfos proto.InternalMessageInfo

func (m *StrategyInfos) GetStrategyInfos() []*StrategyInfo {
	if m != nil {
		return m.StrategyInfos
	}
	return nil
}

func init() {
	proto.RegisterType((*StrategyInfo)(nil), "bitesla.srv.strategy.StrategyInfo")
	proto.RegisterType((*StrategyInfos)(nil), "bitesla.srv.strategy.StrategyInfos")
}

func init() { proto.RegisterFile("proto/strategy.proto", fileDescriptor_8a9cfd4cb1c623bb) }

var fileDescriptor_8a9cfd4cb1c623bb = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x9b, 0xfe, 0xb3, 0x9d, 0xb6, 0x82, 0x43, 0x91, 0xc5, 0x83, 0x84, 0x78, 0xc9, 0x69,
	0x85, 0xfa, 0x15, 0x0a, 0x5a, 0xe8, 0x41, 0xa2, 0x22, 0x15, 0x3c, 0x6c, 0x9b, 0x31, 0x2c, 0xa4,
	0x49, 0xd8, 0xdd, 0x08, 0xfa, 0x39, 0xfc, 0xb2, 0xde, 0x24, 0x9b, 0xa6, 0x8d, 0x50, 0xb0, 0x42,
	0x6f, 0xf3, 0xde, 0x6f, 0xf6, 0xf1, 0x18, 0x58, 0x18, 0x67, 0x2a, 0x35, 0xe9, 0xb5, 0x36, 0x4a,
	0x18, 0x8a, 0x3e, 0xb8, 0x95, 0x38, 0x5e, 0x4a, 0x43, 0x3a, 0x16, 0x5c, 0xab, 0x77, 0x5e, 0x31,
	0xef, 0xab, 0x09, 0xc3, 0x87, 0x8d, 0x98, 0x25, 0x6f, 0x29, 0x72, 0xc0, 0x55, 0xae, 0x14, 0x25,
	0x66, 0x9e, 0x46, 0x32, 0x79, 0xd2, 0xa4, 0x66, 0x53, 0xe6, 0xb8, 0x8e, 0xdf, 0x0a, 0xf6, 0x10,
	0xbc, 0x04, 0xa8, 0xc2, 0x66, 0x21, 0x6b, 0xda, 0xbd, 0x9a, 0x83, 0x08, 0xed, 0x44, 0xac, 0x89,
	0xb5, 0x5c, 0xc7, 0xef, 0x07, 0x76, 0x46, 0x17, 0x06, 0x21, 0xe9, 0x95, 0x92, 0x99, 0x91, 0x69,
	0xc2, 0xda, 0x16, 0xd5, 0x2d, 0x3c, 0x87, 0x6e, 0x29, 0x58, 0xc7, 0xc2, 0x8d, 0x2a, 0xd2, 0x32,
	0x11, 0x11, 0xeb, 0xba, 0x8e, 0xdf, 0x09, 0xec, 0x5c, 0x78, 0x5a, 0x7e, 0x12, 0x3b, 0x29, 0xbd,
	0x62, 0x2e, 0x5a, 0xad, 0x14, 0x09, 0x43, 0x8f, 0x72, 0x4d, 0xac, 0x57, 0xb6, 0xda, 0x39, 0x05,
	0xcf, 0xb3, 0xb0, 0xe2, 0xfd, 0x92, 0xef, 0x1c, 0x6f, 0x01, 0xa3, 0xfa, 0x55, 0x34, 0xde, 0xc1,
	0x48, 0xd7, 0x0d, 0xe6, 0xb8, 0x2d, 0x7f, 0x30, 0xf1, 0xf8, 0xbe, 0xab, 0xf2, 0xfa, 0xdb, 0xe0,
	0xf7, 0xc3, 0xc9, 0x77, 0x13, 0x7a, 0x15, 0xc7, 0x05, 0x0c, 0xe7, 0x52, 0x9b, 0xad, 0x3e, 0x20,
	0xef, 0xe2, 0xea, 0xef, 0x1d, 0xed, 0x35, 0xf0, 0x19, 0x06, 0xf7, 0xf9, 0xff, 0x92, 0x0f, 0xd8,
	0xf1, 0x1a, 0xf8, 0x0a, 0x67, 0xb7, 0xb4, 0x0d, 0x9e, 0x92, 0x11, 0x32, 0x3e, 0x62, 0xfc, 0x0b,
	0x9c, 0x4e, 0x29, 0x26, 0x43, 0xc7, 0xaf, 0xbe, 0xec, 0xda, 0xaf, 0x70, 0xf3, 0x13, 0x00, 0x00,
	0xff, 0xff, 0xc0, 0x87, 0xe7, 0x24, 0x22, 0x03, 0x00, 0x00,
}
