// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/trader.proto

package bitesla_srv_trader

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_STOP    Status = 0
	Status_START   Status = 1
	Status_PENDING Status = 2
	Status_SUCCESS Status = 3
	Status_ERROR   Status = 4
)

var Status_name = map[int32]string{
	0: "STOP",
	1: "START",
	2: "PENDING",
	3: "SUCCESS",
	4: "ERROR",
}

var Status_value = map[string]int32{
	"STOP":    0,
	"START":   1,
	"PENDING": 2,
	"SUCCESS": 3,
	"ERROR":   4,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2edf40fce82c1271, []int{0}
}

type Language int32

const (
	Language_GOLANG Language = 0
	Language_PYTHON Language = 1
)

var Language_name = map[int32]string{
	0: "GOLANG",
	1: "PYTHON",
}

var Language_value = map[string]int32{
	"GOLANG": 0,
	"PYTHON": 1,
}

func (x Language) String() string {
	return proto.EnumName(Language_name, int32(x))
}

func (Language) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2edf40fce82c1271, []int{1}
}

type TraderInfo struct {
	CurrentLoginUserID   int64    `protobuf:"varint,1,opt,name=currentLoginUserID,proto3" json:"currentLoginUserID,omitempty"`
	ExchangeId           int64    `protobuf:"varint,2,opt,name=exchangeId,proto3" json:"exchangeId,omitempty"`
	StrategyId           int64    `protobuf:"varint,3,opt,name=strategyId,proto3" json:"strategyId,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Status               int32    `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CreateTime           int64    `protobuf:"varint,7,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64    `protobuf:"varint,8,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Page                 int32    `protobuf:"varint,9,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,10,opt,name=size,proto3" json:"size,omitempty"`
	TraderId             int64    `protobuf:"varint,11,opt,name=traderId,proto3" json:"traderId,omitempty"`
	ApiKey               string   `protobuf:"bytes,13,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	ApiSecret            string   `protobuf:"bytes,14,opt,name=apiSecret,proto3" json:"apiSecret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TraderInfo) Reset()         { *m = TraderInfo{} }
func (m *TraderInfo) String() string { return proto.CompactTextString(m) }
func (*TraderInfo) ProtoMessage()    {}
func (*TraderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2edf40fce82c1271, []int{0}
}

func (m *TraderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraderInfo.Unmarshal(m, b)
}
func (m *TraderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraderInfo.Marshal(b, m, deterministic)
}
func (m *TraderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraderInfo.Merge(m, src)
}
func (m *TraderInfo) XXX_Size() int {
	return xxx_messageInfo_TraderInfo.Size(m)
}
func (m *TraderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TraderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TraderInfo proto.InternalMessageInfo

func (m *TraderInfo) GetCurrentLoginUserID() int64 {
	if m != nil {
		return m.CurrentLoginUserID
	}
	return 0
}

func (m *TraderInfo) GetExchangeId() int64 {
	if m != nil {
		return m.ExchangeId
	}
	return 0
}

func (m *TraderInfo) GetStrategyId() int64 {
	if m != nil {
		return m.StrategyId
	}
	return 0
}

func (m *TraderInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TraderInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *TraderInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TraderInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *TraderInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *TraderInfo) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *TraderInfo) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *TraderInfo) GetTraderId() int64 {
	if m != nil {
		return m.TraderId
	}
	return 0
}

func (m *TraderInfo) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *TraderInfo) GetApiSecret() string {
	if m != nil {
		return m.ApiSecret
	}
	return ""
}

type TraderInfos struct {
	TraderInfos          []*TraderInfo `protobuf:"bytes,1,rep,name=traderInfos,proto3" json:"traderInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TraderInfos) Reset()         { *m = TraderInfos{} }
func (m *TraderInfos) String() string { return proto.CompactTextString(m) }
func (*TraderInfos) ProtoMessage()    {}
func (*TraderInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_2edf40fce82c1271, []int{1}
}

func (m *TraderInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraderInfos.Unmarshal(m, b)
}
func (m *TraderInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraderInfos.Marshal(b, m, deterministic)
}
func (m *TraderInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraderInfos.Merge(m, src)
}
func (m *TraderInfos) XXX_Size() int {
	return xxx_messageInfo_TraderInfos.Size(m)
}
func (m *TraderInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_TraderInfos.DiscardUnknown(m)
}

var xxx_messageInfo_TraderInfos proto.InternalMessageInfo

func (m *TraderInfos) GetTraderInfos() []*TraderInfo {
	if m != nil {
		return m.TraderInfos
	}
	return nil
}

type StrategyInfo struct {
	CurrentLoginUserID   int64    `protobuf:"varint,1,opt,name=currentLoginUserID,proto3" json:"currentLoginUserID,omitempty"`
	StrategyId           int64    `protobuf:"varint,2,opt,name=strategyId,proto3" json:"strategyId,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Script               string   `protobuf:"bytes,5,opt,name=script,proto3" json:"script,omitempty"`
	Page                 int32    `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	CreateTime           int64    `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64    `protobuf:"varint,9,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Language             int32    `protobuf:"varint,10,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StrategyInfo) Reset()         { *m = StrategyInfo{} }
func (m *StrategyInfo) String() string { return proto.CompactTextString(m) }
func (*StrategyInfo) ProtoMessage()    {}
func (*StrategyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2edf40fce82c1271, []int{2}
}

func (m *StrategyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrategyInfo.Unmarshal(m, b)
}
func (m *StrategyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrategyInfo.Marshal(b, m, deterministic)
}
func (m *StrategyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrategyInfo.Merge(m, src)
}
func (m *StrategyInfo) XXX_Size() int {
	return xxx_messageInfo_StrategyInfo.Size(m)
}
func (m *StrategyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StrategyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StrategyInfo proto.InternalMessageInfo

func (m *StrategyInfo) GetCurrentLoginUserID() int64 {
	if m != nil {
		return m.CurrentLoginUserID
	}
	return 0
}

func (m *StrategyInfo) GetStrategyId() int64 {
	if m != nil {
		return m.StrategyId
	}
	return 0
}

func (m *StrategyInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StrategyInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *StrategyInfo) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *StrategyInfo) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *StrategyInfo) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *StrategyInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *StrategyInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *StrategyInfo) GetLanguage() int32 {
	if m != nil {
		return m.Language
	}
	return 0
}

func init() {
	proto.RegisterEnum("bitesla.srv.trader.Status", Status_name, Status_value)
	proto.RegisterEnum("bitesla.srv.trader.Language", Language_name, Language_value)
	proto.RegisterType((*TraderInfo)(nil), "bitesla.srv.trader.TraderInfo")
	proto.RegisterType((*TraderInfos)(nil), "bitesla.srv.trader.TraderInfos")
	proto.RegisterType((*StrategyInfo)(nil), "bitesla.srv.trader.StrategyInfo")
}

func init() { proto.RegisterFile("proto/trader.proto", fileDescriptor_2edf40fce82c1271) }

var fileDescriptor_2edf40fce82c1271 = []byte{
	// 523 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xc1, 0x6e, 0xd3, 0x4e,
	0x10, 0xc6, 0xe3, 0x38, 0x75, 0xed, 0x71, 0xfe, 0x7f, 0xac, 0x3d, 0xa0, 0x55, 0x84, 0x4a, 0xe4,
	0x53, 0xd4, 0x83, 0x91, 0xca, 0x0b, 0x50, 0x9a, 0x28, 0x58, 0x84, 0xd8, 0xb2, 0xdd, 0x03, 0xc7,
	0xad, 0x3d, 0xa4, 0x96, 0x52, 0xc7, 0xf2, 0x6e, 0x80, 0x72, 0xe6, 0x45, 0x78, 0x03, 0x1e, 0x11,
	0xed, 0xda, 0x8d, 0x0d, 0x29, 0x04, 0xa1, 0xdc, 0xe6, 0xfb, 0x3e, 0xef, 0xcc, 0x68, 0x7e, 0x51,
	0x80, 0x94, 0xd5, 0x46, 0x6c, 0x5e, 0x88, 0x8a, 0x65, 0x58, 0x79, 0x4a, 0x10, 0x72, 0x93, 0x0b,
	0xe4, 0x6b, 0xe6, 0xf1, 0xea, 0xa3, 0x57, 0x27, 0xee, 0x57, 0x1d, 0x20, 0x51, 0xa5, 0x5f, 0x7c,
	0xd8, 0x10, 0x0f, 0x48, 0xba, 0xad, 0x2a, 0x2c, 0xc4, 0x62, 0xb3, 0xca, 0x8b, 0x6b, 0x8e, 0x95,
	0x3f, 0xa5, 0xda, 0x58, 0x9b, 0xe8, 0xd1, 0x23, 0x09, 0x39, 0x03, 0xc0, 0xcf, 0xe9, 0x2d, 0x2b,
	0x56, 0xe8, 0x67, 0xb4, 0xaf, 0xbe, 0xeb, 0x38, 0x32, 0xe7, 0xa2, 0x62, 0x02, 0x57, 0xf7, 0x7e,
	0x46, 0xf5, 0x3a, 0x6f, 0x1d, 0x42, 0x60, 0x50, 0xb0, 0x3b, 0xa4, 0x83, 0xb1, 0x36, 0xb1, 0x22,
	0x55, 0x93, 0xa7, 0x60, 0x70, 0xc1, 0xc4, 0x96, 0xd3, 0x93, 0xb1, 0x36, 0x39, 0x89, 0x1a, 0x45,
	0xc6, 0x60, 0x67, 0xc8, 0xd3, 0x2a, 0x2f, 0x45, 0xbe, 0x29, 0xa8, 0xa1, 0x9e, 0x74, 0x2d, 0x39,
	0x2d, 0xad, 0x90, 0x09, 0x4c, 0xf2, 0x3b, 0xa4, 0xa7, 0xf5, 0xb4, 0xd6, 0x91, 0xf9, 0xb6, 0xcc,
	0x1e, 0x72, 0xb3, 0xce, 0x5b, 0x47, 0x6e, 0x53, 0xb2, 0x15, 0x52, 0x4b, 0xcd, 0x55, 0xb5, 0xf4,
	0x78, 0xfe, 0x05, 0x29, 0xd4, 0x9e, 0xac, 0xc9, 0x08, 0xcc, 0xfa, 0x7c, 0x7e, 0x46, 0x6d, 0xd5,
	0x65, 0xa7, 0xe5, 0xf6, 0xac, 0xcc, 0xdf, 0xe2, 0x3d, 0xfd, 0x4f, 0x2d, 0xd8, 0x28, 0xf2, 0x0c,
	0x2c, 0x56, 0xe6, 0x31, 0xa6, 0x15, 0x0a, 0xfa, 0xbf, 0x8a, 0x5a, 0xc3, 0x0d, 0xc0, 0x6e, 0x29,
	0x70, 0xf2, 0x0a, 0x6c, 0xd1, 0x4a, 0xaa, 0x8d, 0xf5, 0x89, 0x7d, 0x71, 0xe6, 0xed, 0xf3, 0xf3,
	0xda, 0x57, 0x51, 0xf7, 0x89, 0xfb, 0xbd, 0x0f, 0xc3, 0xf8, 0xe1, 0xce, 0xff, 0x48, 0xb6, 0x43,
	0xae, 0xff, 0x5b, 0x72, 0x7a, 0x87, 0xdc, 0x2f, 0x84, 0x06, 0xfb, 0x84, 0x24, 0x5b, 0x25, 0x14,
	0x5b, 0x2b, 0x6a, 0xd4, 0xee, 0xf2, 0xc6, 0x23, 0x97, 0x3f, 0xed, 0x5c, 0xfe, 0x67, 0xc2, 0xe6,
	0x01, 0xc2, 0xd6, 0x1e, 0xe1, 0x11, 0x98, 0x6b, 0x56, 0xac, 0xb6, 0x72, 0x56, 0x4d, 0x74, 0xa7,
	0xcf, 0x5f, 0x83, 0x11, 0xd7, 0xbf, 0x34, 0x13, 0x06, 0x71, 0x12, 0x84, 0x4e, 0x8f, 0x58, 0x70,
	0x12, 0x27, 0x97, 0x51, 0xe2, 0x68, 0xc4, 0x86, 0xd3, 0x70, 0xb6, 0x9c, 0xfa, 0xcb, 0xb9, 0xd3,
	0x97, 0x22, 0xbe, 0xbe, 0xba, 0x9a, 0xc5, 0xb1, 0xa3, 0xcb, 0x8f, 0x66, 0x51, 0x14, 0x44, 0xce,
	0xe0, 0xdc, 0x05, 0x73, 0xd1, 0xf4, 0x23, 0x00, 0xc6, 0x3c, 0x58, 0x5c, 0x2e, 0xe7, 0x4e, 0x4f,
	0xd6, 0xe1, 0xfb, 0xe4, 0x4d, 0xb0, 0x74, 0xb4, 0x8b, 0x6f, 0x3a, 0x18, 0x35, 0x36, 0x12, 0x00,
	0x2c, 0x72, 0x2e, 0x1a, 0x75, 0x00, 0xf0, 0xe8, 0xf9, 0x9f, 0x73, 0xee, 0xf6, 0xc8, 0x3b, 0xb0,
	0xc2, 0xed, 0xdf, 0xf6, 0x3b, 0x90, 0xbb, 0x3d, 0x12, 0xc3, 0x93, 0x39, 0x36, 0xed, 0xa6, 0x28,
	0x58, 0xbe, 0x3e, 0x42, 0xd3, 0x10, 0x86, 0x53, 0x5c, 0xa3, 0xc0, 0xa3, 0xad, 0x19, 0xc2, 0x30,
	0xfe, 0x94, 0x8b, 0xf4, 0xf6, 0x58, 0x1d, 0x6f, 0x0c, 0xf5, 0x8f, 0xf9, 0xf2, 0x47, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xa3, 0x6f, 0x40, 0x27, 0x47, 0x05, 0x00, 0x00,
}
